[package]
name = "pinentry-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.33", default-features = false, features = ["default_fonts", "wayland", "glow", "accesskit"] }
secrecy = "0.10"

[dev-dependencies]
egui_kittest = "0.33"
accesskit = "0.21"

[profile.release]
strip = true
lto = true
